version: '3.5'

services:
  proxy:
    image: traefik:latest
    restart: always
    networks:
      - front
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.toml:/etc/traefik/traefik.toml:ro

networks:
  front:
    name: front
    driver: bridge
