logLevel = "INFO"
defaultEntryPoints = ["http"]

[accessLog]

[web]
address = ":8080"

[entryPoints]
[entryPoints.http]
address = ":80"

[docker]
endpoint = "unix:///var/run/docker.sock"
watch = true
